# GitHub Pages設定
title: "大革命 - あえ麺専門店"
description: "神戸・大阪を中心に展開するあえ麺専門店「大革命」の公式ウェブサイト"
url: "https://daikakumei.com"
baseurl: ""

# プラグイン設定
plugins:
  - jekyll-redirect-from

# パーマリンク設定（.htmlを削除）
permalink: /:title/
permalink: pretty

# 除外ファイル
exclude:
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - .gitignore
  - .stylelintrc.json
